- denops/gin/feat/edit/command.ts
> :bug: Remove temporary file on `GinEdit --cached`

- README.md
- autoload/gin/internal/feat/branch/action.vim
- autoload/gin/internal/feat/branch/core.vim
- denops/gin/feat/branch/command.ts
- denops/gin/feat/branch/main.ts
- denops/gin/feat/branch/parser.ts
- denops/gin/feat/branch/render.ts
- denops/gin/main.ts
- doc/gin.txt
- ftplugin/gin-branch.vim
- plugin/gin-branch.vim
- syntax/gin-branch.vim
> Add `GinBranch` to list and manipulate git branches

- denops/gin/git/process.ts
- denops/gin/global.ts
- denops/gin/util/worktree.ts
> Add `GIN_BUFFER_PROTOCOLS` to detect proper worktree on Gin buffers

- denops/gin/feat/branch/parser.ts
> :bug: Fix `GinBranch` (#29)

- denops/gin/feat/diff/command.ts
- denops/gin/util/worktree.ts
- doc/gin.txt
> Fix issue of handling a git repository on non current working directory

- denops/gin/core/bare/command.ts
- denops/gin/deps.ts
- denops/gin/deps_test.ts
- denops/gin/util/buffer.ts
- denops/gin/util/decoration.ts
- denops/gin/util/text.ts
- denops/gin/util/text_test.ts
- doc/gin.txt
- plugin/gin/colors.vim
- plugin/gin/decoration.vim
> Enable ANSI Escape Code colors on `Gin` command (can be disabled by `++monochrome` option)

- autoload/gin/internal/feat/branch/action.vim
> Improve `GinBranch`

- autoload/gin/component/branch.vim
- autoload/gin/component/traffic.vim
- autoload/gin/component/worktree.vim
- autoload/gin/util.vim
Otherwise components cause this kind of issues.
https://github.com/Shougo/ddu.vim/issues/14
> :bug: Do NOT invoke RPC functions directly from components

- autoload/gin/component/branch.vim
- autoload/gin/component/traffic.vim
- autoload/gin/component/worktree.vim
- autoload/gin/util.vim
- doc/gin.txt
- plugin/gin.vim
> :bug: Do NOT invoke `redrawstatusline` nor `redrawtabline`

- autoload/gin/internal/feat/status/action.vim
- denops/gin/core/proxy/server.ts
- denops/gin/feat/chaperon/command.ts
- denops/gin/feat/status/command.ts
- doc/gin.txt
> 💥  Remove ++plain option from GinChaperon etc.

- denops/gin/feat/diff/command.ts
- denops/gin/feat/edit/command.ts
- denops/gin/feat/patch/command.ts
- ftplugin/gin-diff.vim
- syntax/gin-diff.vim
> :bug: Fix `GinPatch`

- denops/gin/feat/status/action.ts
> :bug: Fix 'unrecognized argument' issue on 'edit:cached'

- README.md
- doc/gin.txt
- plugin/gin-cd.vim
> :+1: Add `GinCd/GinLcd/GinTcd` commands

- denops/gin/feat/diff/command.ts
- denops/gin/feat/edit/command.ts
> :bug: Fix relative path issue on `GinEdit/GinDiff`

- denops/gin/component/branch.ts
> :bug: Use 'branch --show-current' as a fallback

- denops/gin/action/core.ts
- denops/gin/action/yank.ts
- denops/gin/command/branch/edit.ts
- denops/gin/command/log/edit.ts
- denops/gin/command/status/edit.ts
- ftplugin/gin-branch.vim
- ftplugin/gin-log.vim
- ftplugin/gin-status.vim
> Add `yank:xxxxx` actions to copy candidate information

- denops/gin/git/executor.ts
- denops/gin/git/process.ts
- denops/gin/git/process_test.ts
> :+1: Use `Deno.Command` instead of `Deno.run`

- autoload/gin/indicator/echo.vim
- autoload/gin/indicator/null.vim
- denops/gin/action/add.ts
- denops/gin/command/bare/command.ts
- denops/gin/command/buffer/edit.ts
- denops/gin/command/edit/edit.ts
- denops/gin/command/edit/read.ts
- denops/gin/git/executor.ts
- denops/gin/util/indicator_stream.ts
Now Gin echo stdout/stderr during process execution as progress indication.
> Add progress (stdout/stderr) inidicator to `Gin` command

- autoload/gin/internal/proxy.vim
> :bug: Fix regexp for confirm dialog

- autoload/gin/indicator/null.vim
- denops/gin/action/yank.ts
- denops/gin/component/branch.ts
- denops/gin/component/traffic.ts
- denops/gin/component/worktree.ts
- denops/gin/git/executor.ts
- denops/gin/git/finder.ts
- denops/gin/util/__snapshots__/ansi_escape_code_test.ts.snap
- denops/gin/util/ansi_escape_code_test.ts
- denops/gin/util/cmd_test.ts
- denops/gin/util/testdata/ansi_escape_code_content.txt
- denops/gin/util/testutil.ts
- denops/gin/util/yank.ts
- denops/gin/util/yank_test.ts
> :muscle: Refactoring

- denops/gin/command/edit/write.ts
> :bug: Fix `GinEdit` cannot apply filemode

- denops/gin/action/branch_new.ts
> :bug: Use `target` instead for `branch_new` action

- .github/workflows/test.yml
- .github/workflows/udd.yml
> :coffee: Upgrade GitHub Actions

- denops/gin/command/browse/command.ts
- denops/gin/command/browse/main.ts
> :bug: Fix `GinBrowse`
